---
- hosts: all
  roles:

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro

  # cli
  # shell tooling
  - role: git
    git_user_name: Mikko Kokkonen
    git_user_email: mikko@mikian.com
  - role: hub
  ## languages
  - role: rbenv
