---
- hosts: all
  roles:

  # osx config
  - role: dock
    apps:
    - /Applications/Firefox.app
    - /Applications/Airmail.app
    - /Applications/Dashlane.app
    - /Applications/Spotify.app
    - /Applications/Airmail.app
    - "/Applications/Adobe Photoshop CC/Adobe Photoshop CC.app"
    - "/Applications/Adobe Illustrator CC/Adobe Illustrator.app"
    - /Applications/Atom.app
    - /Applications/iTerm.app
    - /Applications/Dash.app
    folders:
    - path: ~/
    - path: ~/Documents
    - path: ~/Downloads
      sort: datemodified
  - role: dashboard
    disabled: YES

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-sauce-code-powerline

  # cli
  # shell tooling
  - role: git
    git_user_name: Bob Bob
    git_user_email: bob.bob@example.com
  - role: legit
  - role: hub
  - role: brew_package
    package_name: vim
  ## languages
  - role: brew_package
    package_name: node
  - role: rbenv
  - role: npm_package
    package_name: grunt
  - role: npm_package
    package_name: bower
