---
- hosts: all
  roles:

  # fonts
  - role: cask_package
    tap: caskroom/fonts
    package_name: font-source-code-pro

  # cli
  # shell tooling
  - role: git
    git_user_name: Mikko Kokkonen
    git_user_email: mikko@mikian.com
  - role: hub
  - role: brew_package
    package_name: ack
  - role: brew_package
    package_name: ctags
  - role: brew_package
    package_name: git-flow
  - role: brew_package
    package_name: git-flow-clone
  - role: brew_package
    package_name: mitmproxy
  - role: brew_package
    package_name: mobile-shell
  - role: brew_package
    package_name: mogenerator
  - role: brew_package
    package_name: pow
  - role: brew_package
    tap: thoughtbot/formulae
    package_name: rcm
  - role: brew_package
    package_name: rename
  - role: brew_package
    package_name: ssh-copy-id
  - role: brew_package
    package_name: the_silver_searcher
  - role: brew_package
    package_name: tig
  - role: brew_package
    package_name: uncrustify
  - role: brew_package
    package_name: watch
  - role: brew_package
    package_name: xctool
  - role: brew_package
    package_name: zsh

  ## languages
  - role: rbenv
    rubies:
      - 2.1.2
    global: 2.1.2
  - role: brew_package
    package_name: python

  ## databases
  - role: brew_package
    package_name: redis
  - role: brew_package
    package_name: rethinkdb

  ## deployment
  - role: brew_package
    package_name: heroku-toolbelt

  ## Casks
  - role: cask_package
    package_name: betterzipql
  - role: cask_package
    package_name: charles
  - role: cask_package
    package_name: firefox
  - role: cask_package
    package_name: gpgtools
  - role: cask_package
    package_name: hockeyapp
  - role: cask_package
    package_name: iexplorer
  - role: cask_package
    package_name: ksdiff
  - role: cask_package
    tap: jimbojsb/launchrocket
    package_name: launchrocket
  - role: cask_package
    package_name: mactex
  - role: cask_package
    package_name: pandoc
  - role: cask_package
    package_name: papers
  - role: cask_package
    package_name: provisioning
  - role: cask_package
    package_name: qlstephen
  - role: cask_package
    package_name: rescuetime
  - role: cask_package
    package_name: spark-inspector
  - role: cask_package
    package_name: sublime-text3
  - role: cask_package
    package_name: suspicious-package
  - role: cask_package
    package_name: uncrustifyx
